const $=id=>document.getElementById(id);
const game=new CrowdGame(CONFIG);
const crowdFlow=new CrowdFlow($("crowd-layer"),CONFIG,game);
game.crowdCountProvider=()=>crowdFlow.counts();
let policy='standard',commentBucket=-1,lastEvent=-1,saved=false,lastGoalNotice='';
const yen=n=>'¥'+n.toLocaleString('ja-JP');
const place=id=>CONFIG.places.find(p=>p.id===id);
function readRanking(){try{const data=JSON.parse(localStorage.getItem(CONFIG.rankingKey)||'[]');return Array.isArray(data)?data.filter(r=>r&&Number.isFinite(r.profit)&&Number.isFinite(r.sold)&&typeof r.date==='string').sort((a,b)=>b.profit-a.profit).slice(0,5):[];}catch{return [];}}
function rankingHTML(rows){return rows.length?rows.map((r,i)=>`<div class="rank-row"><b>${String(i+1).padStart(2,'0')}</b><span>${escapeHTML(r.date)}<small>${r.sold}個販売</small></span><strong>${yen(r.profit)}</strong></div>`).join(''):'<p class="empty-rank">まだ記録はありません。最初の記録をつくろう。</p>';}
function escapeHTML(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const PLACE_ICONS={
 lobby:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2z"/>',
 cafe:'<path d="M5 9h13v6a5 5 0 0 1-5 5h-3a5 5 0 0 1-5-5z"/><path d="M18 11h1a3 3 0 1 1 0 6h-2M8 4v2m5-3v3"/>',
 experience:'<path d="M7 9h10a5 5 0 0 1 4.7 6.7l-1 2.5a2 2 0 0 1-3.2.7L14 16h-4l-3.5 2.9a2 2 0 0 1-3.2-.7l-1-2.5A5 5 0 0 1 7 9z"/><path d="M7 12v4m-2-2h4m7-1h.01M18 15h.01"/>',
 theater:'<path d="M16 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="10" cy="7" r="4"/><path d="M20 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/>',
 booth:'<path d="M5 9h14l1 12H4z"/><path d="M9 9V6a3 3 0 0 1 6 0v3"/>',
 soccer:'<circle cx="12" cy="12" r="9"/><path d="m12 7 4 3-1.5 5h-5L8 10zm0 0V3m4 7 5-2m-6.5 7 3 5M9.5 15l-3 4M8 10l-5-2"/>'
};
$('hotspots').innerHTML=CONFIG.places.map((p,i)=>`<button class="hotspot" data-place="${p.id}" style="left:${p.x}%;top:${p.y}%" aria-label="${p.name}を選ぶ"><span class="spot-icon ${p.id}" aria-hidden="true"><svg viewBox="0 0 24 24">${PLACE_ICONS[p.id]}</svg></span><span class="spot-label"><b>${String(i+1).padStart(2,'0')}</b>${p.short}</span></button>`).join('');
$('product').innerHTML=CONFIG.products.map((p,i)=>`<option value="${i}">${p.name}</option>`).join('');
function showComments(){if(game.selected!==game.location){$('comments').innerHTML='<div class="voice-placeholder">この場所には、どんな声があるだろう。<br>移動して来場者の話を聞いてみよう。</div>';return;}$('comments').innerHTML=game.comments().map((text,i)=>`<div class="comment"><span class="avatar a${i}">${['◉','✦','◈'][i]}</span><p>${text}</p></div>`).join('');}
function renderQuantity(){const i=Number($('product').value),old=Number($('quantity').value)||1;$('quantity').innerHTML=game.inventory[i]?Array.from({length:game.inventory[i]},(_,i)=>`<option value="${i+1}">${i+1} 個</option>`).join(''):'<option value="0">在庫なし</option>';$('quantity').value=String(Math.min(old,game.inventory[i]));render();}
function render(){const remaining=Math.max(0,Math.ceil(CONFIG.duration-game.elapsed));$('timer').innerHTML=`${String(Math.floor(remaining/60)).padStart(2,'0')}<span>:</span>${String(remaining%60).padStart(2,'0')}`;$('timer').classList.toggle('urgent',remaining<=30);$('time-progress').style.width=`${remaining/CONFIG.duration*100}%`;$('profit').textContent=yen(game.profit);$('revenue').textContent=yen(game.revenue);$('sold-count').textContent=game.sold+' 個';$('goal-bonus').textContent=yen(game.goalBonus);$('inventory-total').textContent=game.inventory.reduce((a,b)=>a+b,0)+'個';$('inventory').innerHTML=CONFIG.products.map((p,i)=>`<div class="inventory-row ${game.inventory[i]===0?'sold-out':''}"><span class="product-icon">${p.icon}</span><span>${p.name}</span><b>${game.inventory[i]}<small> 個</small></b></div>`).join('');renderGoals();
 const selected=place(game.selected);$('selected-name').textContent=selected.name;document.querySelectorAll('.hotspot').forEach(b=>{b.classList.toggle('selected',b.dataset.place===game.selected);b.setAttribute('aria-pressed',b.dataset.place===game.selected);b.disabled=!!game.busy||!game.running;});
 const visitors=crowdFlow.counts()[game.selected]||0;$('crowd-signal').textContent=`このエリアを歩く人　${visitors}人`;$('crowd-signal').classList.toggle('busy',visitors>=7);
 const move=game.busy?.kind==='move';$('location-text').textContent=move?`移動中 → ${selected.name}`:`現在地：${place(game.location).name}`;$('move-button').disabled=!game.running||!!game.busy||game.selected===game.location;$('move-button').textContent=move?'移動中…':game.selected===game.location?'現在地':`ここへ移動 · ${game.travelSeconds(game.selected)}秒 →`;
 $('map-move-button').disabled=$('move-button').disabled;$('map-move-button').textContent=$('move-button').textContent;
 const index=Number($('product').value),p=CONFIG.products[index];$('cost').textContent=`仕入れ ${yen(p.cost)} / 個`;$('unit-price').textContent=`販売 ${yen(Math.round(p.price*CONFIG.policies[policy].price/10)*10)} / 個`;
 const locked=!game.running||!!game.busy||game.selected!==game.location;$('sell-button').disabled=locked||game.inventory[index]===0;$('product').disabled=locked;$('quantity').disabled=locked||game.inventory[index]===0;[...$('product').options].forEach((o,i)=>{o.disabled=game.inventory[i]===0;});document.querySelectorAll('[data-policy]').forEach(b=>{b.disabled=locked;b.classList.toggle('active',b.dataset.policy===policy);b.setAttribute('aria-pressed',b.dataset.policy===policy);});
 $('sell-button').innerHTML=game.busy?.kind==='sale'?'販売中… 声をかけています':game.inventory[index]===0?'この商品は売り切れ':'この場所で販売する <span>↗</span>';
 const seconds=game.busy?Math.max(0,Math.ceil((game.busy.end-performance.now())/1000)):0;$('next-action').textContent=!game.running?'ゲーム開始でタイマーが動きます':move?`到着まで ${seconds}秒`:game.busy?`販売完了まで ${seconds}秒`:game.selected!==game.location?'↓「ここへ移動」で売り場へ':game.inventory.every(n=>!n)?'完売！閉場まで会場の流れを見てみよう':'声を読んで、商品と価格を選ぼう';
 $('phase').textContent=game.phase().name;$('announcement').textContent=game.event().text;
}
function renderGoals(){const goals=game.goals||[];$('goals').innerHTML=goals.map((goal,i)=>{const product=CONFIG.products.find(p=>p.id===goal.productId);const seconds=Math.max(0,Math.ceil(goal.deadline-game.elapsed));const deadline=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}まで`;const progress=goal.status==='complete'?`${goal.quantity}/${goal.quantity}個 · 達成！`:goal.status==='failed'?`${goal.progress}/${goal.quantity}個 · 時間切れ`:`${goal.progress}/${goal.quantity}個 · ${deadline}`;return `<article class="goal-row ${goal.status}"><div class="goal-topline"><b>${String(i+1).padStart(2,'0')}　${goal.title}</b><strong>+${yen(goal.reward)}</strong></div><div class="goal-description">${goal.description}</div><div class="goal-progress-line"><span>${progress}</span><span class="goal-track"><i style="width:${goal.status==='complete'?100:goal.progress/goal.quantity*100}%"></i></span></div></article>`;}).join('');if(game.goalNotice&&game.goalNotice!==lastGoalNotice){lastGoalNotice=game.goalNotice;const notice=$('goal-notice');notice.textContent=game.goalNotice;notice.classList.add('visible');const message=game.goalNotice;setTimeout(()=>{if(notice.textContent===message)notice.classList.remove('visible');},4200);}}
let playerMotionTimers=[];
function setPlayer(target,seconds=0){playerMotionTimers.forEach(clearTimeout);playerMotionTimers=[];const destination=crowdFlow.placePoint(target),snapTo=end=>{$('player').style.transitionDuration=end+'s';$('player').style.left=destination.x+'%';$('player').style.top=(destination.y-7)+'%';};if(!seconds||!game.running){snapTo('0s');return;}const source=crowdFlow.placePoint(game.location),hops=crowdFlow.routeBetween(game.location,target),points=hops.map(hop=>({x:hop.x,y:hop.y-7}));points.push({x:destination.x,y:destination.y-7});let previous={x:source.x,y:source.y-7};const distances=points.map(point=>{const distance=Math.hypot((point.x-previous.x)*10,(point.y-previous.y)*(20/3));previous=point;return distance;});const total=distances.reduce((sum,distance)=>sum+distance,0);let delay=0;for(let i=0;i<points.length;i++){const duration=total?seconds*distances[i]/total:seconds;const point=points[i];playerMotionTimers.push(setTimeout(()=>{$('player').style.transitionDuration=`${Math.max(.05,duration)}s`;$('player').style.left=point.x+'%';$('player').style.top=point.y+'%';},delay*1000));delay+=duration;}}
function saleResult(){const r=game.lastResult;if(!r)return;const p=CONFIG.products[r.index];$('sale-result').innerHTML=`<b>${p.name} ${r.quantity}個出して、${r.sold}個売れました。</b><br>単価 ${yen(r.price)} · 売上 ${yen(r.revenue)} · 利益 ${yen(r.profit)} · 残り ${r.remaining}個${r.sold===0?'<p>今は欲しい人が少ないようです。価格を下げるか、別の場所・商品を試そう。</p>':''}`;}
function start(){game.start(performance.now());crowdFlow.reset();policy='standard';commentBucket=-1;lastEvent=-1;lastGoalNotice='';saved=false;$('product').value='0';$('sale-result').textContent='まずは声を聞いて、最初の商品を選ぼう。';setPlayer('lobby');$('welcome').close();$('results').close();renderQuantity();showComments();window.scrollTo({top:0,behavior:'instant'});}
function finish(){if(saved)return;saved=true;$('help').close();saleResult();const summary=game.summary();$('final-profit').textContent=yen(summary.profit);const achieved=game.goals.filter(g=>g.status==='complete').length;$('evaluation').textContent=achieved===2?'2つの目標を達成！読みと判断が光った！':achieved===1?'目標達成ボーナスを獲得！別ルートも試してみよう。':summary.sold>=30?'来場者の流れを読むのが上手い！':game.productSales[3]>=2?'高単価商品の売り方が光った！':summary.sold>=12?'いい読み！次はイベントの変化も追いかけよう。':'次はコメントをヒントに、売り場や価格を変えてみよう。';$('result-stats').innerHTML=[['総売上',yen(summary.revenue)],['目標報酬',yen(summary.goalBonus)],['販売個数',summary.sold+'個'],['売れ残り',summary.remaining+'個'],['最も稼げた場所',summary.place],['最も売れた商品',summary.product]].map(([label,value])=>`<div><span>${label}</span><b>${value}</b></div>`).join('');const record={profit:summary.profit,sold:summary.sold,date:new Date().toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})};const records=[...readRanking(),record].sort((a,b)=>b.profit-a.profit).slice(0,5);try{localStorage.setItem(CONFIG.rankingKey,JSON.stringify(records));$('save-status').textContent=records.includes(record)?'今回の記録がTOP 5に入りました。保存済みです。':'プレイ終了。次はTOP 5を目指そう！';}catch{$('save-status').textContent='ブラウザの保存が制限されています。今回の記録は再読み込みすると消えます。';}$('ranking').innerHTML=rankingHTML(records);$('next-action').textContent='終了！結果を確認しよう';$('results').showModal();}
function tick(){const event=game.tick(performance.now());if(event==='moved'){showComments();}if(event==='sold'){saleResult();renderQuantity();}if(game.running){const bucket=Math.floor(game.elapsed/CONFIG.commentSeconds);if(bucket!==commentBucket||lastEvent!==game.event().at){commentBucket=bucket;lastEvent=game.event().at;if(!game.busy)showComments();}render();}if(event==='finished'){render();finish();}}
$('hotspots').addEventListener('click',e=>{const b=e.target.closest('[data-place]');if(!b||game.busy||!game.running)return;game.selected=b.dataset.place;showComments();render();});
$('move-button').onclick=()=>{tick();const seconds=game.travelSeconds(game.selected);if(game.move(game.selected,performance.now())){setPlayer(game.selected,seconds);$('comments').innerHTML='<div class="voice-placeholder">売り場へ移動中…<br>到着すると来場者の声が聞こえます。</div>';render();}};
$('map-move-button').onclick=()=>$('move-button').click();
$('sell-button').onclick=()=>{tick();if(game.sell(Number($('product').value),Number($('quantity').value),policy,performance.now()))render();};
$('product').onchange=renderQuantity;document.querySelectorAll('[data-policy]').forEach(b=>b.onclick=()=>{policy=b.dataset.policy;render();});$('start-button').onclick=start;$('restart-button').onclick=start;$('help-button').onclick=()=>$('help').showModal();$('close-help').onclick=()=>$('help').close();['welcome','results'].forEach(id=>$(id).addEventListener('cancel',e=>e.preventDefault()));document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick();});
setInterval(tick,150);setPlayer('lobby');renderQuantity();showComments();const initialRanking=readRanking();if(initialRanking.length)$('welcome-ranking').innerHTML='<h3>LOCAL TOP 5</h3>'+rankingHTML(initialRanking);$('welcome').showModal();
