/* Visitors and the seller follow a hand-mapped walkable-path graph. */
class CrowdFlow {
 constructor(canvas,config,game){this.canvas=canvas;this.config=config;this.game=game;this.ctx=canvas.getContext('2d');this.network=config.crowd;this.walkers=[];this.lastFrame=0;this.lastRetarget=0;this.width=0;this.height=0;this.running=true;this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas.parentElement);this.resize();this.reset();requestAnimationFrame(t=>this.frame(t));}
 rand(min,max){return min+Math.random()*(max-min);}
 pickWeighted(weights){const keys=Object.keys(weights);let n=Math.random()*keys.reduce((sum,key)=>sum+weights[key],0);for(const key of keys){n-=weights[key];if(n<=0)return key;}return keys.at(-1);}
 distribution(elapsed){const snapshots=this.network.phases.filter(item=>item.at<=elapsed);const source=snapshots.at(-1)?.weights||this.network.phases[0].weights;const weights={...source};for(const event of this.network.eventBoosts){const age=elapsed-event.at;if(age>=0&&age<48)for(const [zone,amount] of Object.entries(event.weights))weights[zone]=(weights[zone]||0)+amount*(1-age/48);}return weights;}
 randomStop(zone){const stops=this.network.stops[zone];return stops[Math.floor(Math.random()*stops.length)];}
 point(node){const [x,y]=this.network.navNodes[node];return {x,y};}
 counts(){const counts=Object.fromEntries(Object.keys(this.network.stops).map(id=>[id,0]));for(const walker of this.walkers)counts[walker.zone]=(counts[walker.zone]||0)+1;return counts;}
 reset(){const weights=this.distribution(0);this.walkers=Array.from({length:this.network.count},(_,i)=>{const zone=this.pickWeighted(weights),node=this.randomStop(zone);return {zone,node,pos:this.point(node),route:[],targetNode:node,targetZone:zone,speed:this.rand(...this.network.speed),size:this.rand(.84,1.16),color:this.network.outfitColors[Math.floor(Math.random()*this.network.outfitColors.length)],timer:this.rand(0,7)+i*.17,phase:this.rand(0,Math.PI*2)};});this.lastRetarget=0;}
 resize(){const rect=this.canvas.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1);this.width=rect.width;this.height=rect.height;if(!rect.width||!rect.height)return;this.canvas.width=Math.round(rect.width*dpr);this.canvas.height=Math.round(rect.height*dpr);this.ctx.setTransform(dpr,0,0,dpr,0,0);}
 findPath(start,end){if(start===end)return[start];const queue=[start],previous=new Map([[start,null]]);while(queue.length){const node=queue.shift();if(node===end)break;for(const [a,b] of this.network.navEdges){const next=a===node?b:b===node?a:null;if(next&&!previous.has(next)){previous.set(next,node);queue.push(next);}}}if(!previous.has(end))return[];const path=[];for(let node=end;node;node=previous.get(node))path.push(node);return path.reverse();}
 routeBetween(from,to){const starts=this.network.stops[from]||[from],ends=this.network.stops[to]||[to];let best=null;for(const start of starts)for(const end of ends){const path=this.findPath(start,end);if(path.length&&(!best||path.length<best.length))best=path;}return best?best.slice(1).map(node=>({node,...this.point(node)})):[];}
 placePoint(placeId){const stop=this.network.stops[placeId]?.[0];return stop?this.point(stop):this.point('lEntry');}
 assign(walker,weights){const zone=this.pickWeighted(weights);let node=this.randomStop(zone);if(zone===walker.zone&&node===walker.node){const alternatives=this.network.stops[zone].filter(id=>id!==walker.node);if(alternatives.length)node=alternatives[Math.floor(Math.random()*alternatives.length)];}walker.targetNode=node;walker.targetZone=zone;walker.route=this.findPath(walker.node,node).slice(1).map(id=>({node:id,...this.point(id)}));}
 retarget(elapsed){const weights=this.distribution(elapsed);for(const walker of this.walkers)if(walker.route.length===0&&walker.timer<=0){this.assign(walker,weights);walker.timer=this.rand(...this.network.retargetSeconds);}}
 advance(dt,elapsed){this.lastRetarget+=dt;if(this.lastRetarget>=3){this.lastRetarget=0;this.retarget(elapsed);}for(const walker of this.walkers){walker.phase+=dt*8;if(walker.route.length===0)walker.timer-=dt;let budget=walker.speed*dt;while(budget>0&&walker.route.length){const next=walker.route[0],dx=(next.x-walker.pos.x)*10,dy=(next.y-walker.pos.y)*(20/3),distance=Math.hypot(dx,dy);if(distance<.01){walker.pos=this.point(next.node);walker.node=next.node;walker.route.shift();continue;}const step=Math.min(budget,distance),ratio=step/distance;walker.pos.x+=(next.x-walker.pos.x)*ratio;walker.pos.y+=(next.y-walker.pos.y)*ratio;budget-=step;if(step<distance)break;walker.pos=this.point(next.node);walker.node=next.node;walker.route.shift();}if(walker.node===walker.targetNode)walker.zone=walker.targetZone;}}
 drawWalker(w){const x=w.pos.x*this.width/100,y=w.pos.y*this.height/100,s=Math.max(.82,Math.min(1.2,this.width/850))*w.size,step=Math.sin(w.phase)*2*s,c=this.ctx;c.save();c.translate(x,y);c.scale(s,s);c.fillStyle='#17231e49';c.beginPath();c.ellipse(0,1,5.8,2.2,0,0,Math.PI*2);c.fill();c.lineCap='round';c.lineWidth=2.5;c.strokeStyle='#4a4038';c.beginPath();c.moveTo(-1.5,-3);c.lineTo(-2+step,-.2);c.moveTo(1.5,-3);c.lineTo(2-step,-.2);c.stroke();c.fillStyle=w.color;c.beginPath();c.roundRect(-3.5,-12.5,7,9,2);c.fill();c.lineWidth=1;c.strokeStyle='#ffffffd9';c.stroke();c.strokeStyle=w.color;c.lineWidth=2;c.beginPath();c.moveTo(-2.4,-10);c.lineTo(-4,-6);c.moveTo(2.4,-10);c.lineTo(4,-6);c.stroke();c.fillStyle='#ffe0bd';c.beginPath();c.arc(0,-15,3.1,0,Math.PI*2);c.fill();c.fillStyle='#594638';c.beginPath();c.arc(0,-16,3.2,Math.PI,Math.PI*2);c.fill();c.restore();}
 frame(now){if(!this.running)return;const dt=this.lastFrame?Math.min(.06,(now-this.lastFrame)/1000):0;this.lastFrame=now;if(this.width&&this.height){this.ctx.clearRect(0,0,this.width,this.height);if(dt&&!document.hidden)this.advance(dt,this.game.running?this.game.elapsed:0);for(const walker of this.walkers)this.drawWalker(walker);}requestAnimationFrame(t=>this.frame(t));}
 destroy(){this.running=false;this.resizeObserver.disconnect();}
}
if(typeof module!=='undefined')module.exports=CrowdFlow;
