(function(root){
class CrowdGame {
 constructor(config,random=Math.random){this.config=config;this.random=random;this.crowdCountProvider=null;this.reset();}
 reset(){this.running=false;this.startedAt=0;this.elapsed=0;this.location='lobby';this.selected='lobby';this.busy=null;this.revenue=0;this.profit=0;this.goalBonus=0;this.sold=0;this.inventory=this.config.products.map(p=>p.stock);this.productSales=this.inventory.map(()=>0);this.placeProfit=Object.fromEntries(this.config.places.map(p=>[p.id,0]));this.lastResult=null;this.goals=[];this.goalNotice='';}
 start(now){this.reset();this.startedAt=now;this.running=true;const pool=[...this.config.goals];for(let i=pool.length-1;i>0;i--){const j=Math.floor(this.random()*(i+1));[pool[i],pool[j]]=[pool[j],pool[i]];}for(const candidate of pool){if(this.goals.length>=this.config.goalCount)break;if(this.goals.some(g=>g.placeId===candidate.placeId))continue;this.goals.push({...candidate,progress:0,status:'active'});}}
 phase(){return this.config.phases.filter(p=>p.at<=this.elapsed).at(-1);}
 event(){return this.config.events.filter(p=>p.at<=this.elapsed).at(-1);}
 crowdCounts(){return this.crowdCountProvider?.()||null;}
 crowdFactor(place){const counts=this.crowdCounts();if(!counts)return 1;const total=Object.values(counts).reduce((sum,count)=>sum+count,0);if(!total)return 1;const crowd=this.config.crowd,phase=crowd.phases.filter(item=>item.at<=this.elapsed).at(-1)||crowd.phases[0],weights={...phase.weights};for(const event of crowd.eventBoosts){const age=this.elapsed-event.at;if(age>=0&&age<48)for(const [zone,amount] of Object.entries(event.weights))weights[zone]=(weights[zone]||0)+amount*(1-age/48);}const weightTotal=Object.values(weights).reduce((sum,value)=>sum+value,0);const expected=(weights[place]||0)/weightTotal;if(!expected)return crowd.demandFactor.min;const observed=(counts[place]||0)/total,ratio=observed/expected,settings=crowd.demandFactor;return Math.max(settings.min,Math.min(settings.max,1+(ratio-1)*settings.strength));}
 demand(place,index){const area=this.config.places.find(p=>p.id===place),base=area.base[index]+(this.phase().boost[place]?.[index]||0)+(this.event().boost[place]?.[index]||0);return Math.max(.01,Math.min(.98,base*this.crowdFactor(place)));}
 travelSeconds(target){const a=this.config.places.find(p=>p.id===this.location),b=this.config.places.find(p=>p.id===target),leg=(from,to)=>2+Math.hypot(from.x-to.x,from.y-to.y)/18+(from.group!==to.group?2:0);if(a.room&&b.room&&a.room!=='lobby'&&b.room!=='lobby'&&a.room!==b.room){const lobby=this.config.places.find(p=>p.id==='lobby');return Math.round(leg(a,lobby)+leg(lobby,b)+3);}return Math.round(leg(a,b));}
 move(target,now){if(!this.running||this.busy||target===this.location||!this.config.places.some(p=>p.id===target))return false;this.selected=target;this.busy={kind:'move',target,end:now+this.travelSeconds(target)*1000};return true;}
 sell(index,quantity,policy,now){if(!this.running||this.busy||this.selected!==this.location||!Number.isInteger(index)||!this.config.products[index]||!Number.isInteger(quantity)||quantity<1||quantity>this.inventory[index]||!this.config.policies[policy])return false;this.busy={kind:'sale',index,quantity,policy,end:now+this.config.saleSeconds*1000};return true;}
 tick(now){if(!this.running)return null;this.elapsed=Math.min(this.config.duration,Math.max(0,(now-this.startedAt)/1000));let event=null;const deadline=this.startedAt+this.config.duration*1000;
 if(this.busy&&now>=this.busy.end&&this.busy.end<=deadline){const action=this.busy;this.busy=null;if(action.kind==='move'){this.location=action.target;event='moved';}else{const observedElapsed=this.elapsed;this.elapsed=(action.end-this.startedAt)/1000;this.lastResult=this.resolveSale(action);this.elapsed=observedElapsed;event='sold';}}
 this.updateGoals();if(now>=deadline){this.running=false;this.busy=null;return 'finished';}return event;}
 updateGoals(sale=null){for(const goal of this.goals){if(goal.status!=='active')continue;if(sale&&this.location===goal.placeId&&sale.index===this.config.products.findIndex(p=>p.id===goal.productId)&&(!goal.afterEvent||this.elapsed>=goal.afterEvent)){goal.progress=Math.min(goal.quantity,goal.progress+sale.sold);if(goal.progress>=goal.quantity){goal.status='complete';this.goalBonus+=goal.reward;this.profit+=goal.reward;this.goalNotice=`目標達成！「${goal.title}」報酬 +¥${goal.reward.toLocaleString('ja-JP')}`;continue;}}if(this.elapsed>=goal.deadline){goal.status='failed';this.goalNotice=`目標終了：「${goal.title}」`;}}}
 resolveSale({index,quantity,policy}){const p=this.config.products[index],strategy=this.config.policies[policy],counts=this.crowdCounts(),localCount=counts?.[this.location];const hasFootfall=localCount!==undefined,market=this.config.crowd.market,offered=hasFootfall?Math.min(quantity,Math.ceil(localCount*market.buyersPerVisitor)):quantity;const chance=Math.min(.99,this.demand(this.location,index)*strategy.demand*(hasFootfall?market.conversion:1));const variation=(this.random()-.5)*.16;let sold=Math.floor(offered*Math.max(0,Math.min(1,chance+variation))+this.random());sold=Math.min(quantity,sold);const price=Math.round(p.price*strategy.price/10)*10,revenue=sold*price,profit=sold*(price-p.cost);this.inventory[index]-=sold;this.productSales[index]+=sold;this.placeProfit[this.location]+=profit;this.sold+=sold;this.revenue+=revenue;this.profit+=profit;const result={index,quantity,sold,price,revenue,profit,remaining:this.inventory[index]};this.updateGoals(result);return result;}
 comments(){const p=this.config.places.find(p=>p.id===this.location);const available=this.config.products.map((product,index)=>({product,weight:Math.pow(this.demand(p.id,index),2)}));const comments=[];for(let n=0;n<2;n++){let r=this.random()*available.reduce((s,x)=>s+x.weight,0);let i=available.findIndex(x=>(r-=x.weight)<=0);if(i<0)i=available.length-1;const chosen=available.splice(i,1)[0].product;comments.push(chosen.comments[Math.floor(this.random()*chosen.comments.length)]);}const counts=this.crowdCounts(),count=counts?.[p.id];comments.push(count!==undefined&&count<=2?'人通りが少ないね。もう少し待ってみようかな。':count>=7?'この辺り、次々に人が通っていくね。':p.chat[Math.floor(this.random()*p.chat.length)]);return comments;}
 summary(){const bestPlace=Object.entries(this.placeProfit).sort((a,b)=>b[1]-a[1])[0];const bestIndex=this.productSales.indexOf(Math.max(...this.productSales));return {profit:this.profit,revenue:this.revenue,goalBonus:this.goalBonus,sold:this.sold,remaining:this.inventory.reduce((a,b)=>a+b,0),place:this.sold?this.config.places.find(p=>p.id===bestPlace[0]).name:'販売なし',product:this.sold?this.config.products[bestIndex].name:'販売なし'};}
}
root.CrowdGame=CrowdGame;if(typeof module!=='undefined')module.exports=CrowdGame;
})(typeof window!=='undefined'?window:globalThis);
